name: Build with PyInstaller

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name Dandilion --add-data "app:app" --icon=assets/icon.ico main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Dandilion
        path: dist/Dandilion